# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tyler Van Schaick
# email: your-email@example.com
# Site description
# description: >- # this means to ignore newlines until "baseurl:"
  # Front-end web developer.
# baseurl: / # the subpath of your site, e.g. /blog
# url: "https://www.tylervanschaick.com" # the base hostname & protocol for your site, e.g. http://example.com

social_accounts:
  LinkedIn: https://www.linkedin.com/in/tylervs
  GitHub:  https://github.com/tyler-vs

# Google Analytics account key
google_analytics_key: UA-146797023-1

# Build settings
markdown: kramdown
remote_theme: adobe/hyde-theme@v1.0.0
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Pagination
# paginate: 1


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - docs

# Determine the Sass directory as
# seen on this guide: https://jekyllrb.com/docs/assets/
# sass:
#   sass_dir: _sass

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: tylervanschaick-com

# Create a jekyll collection for "projects".
collections:
  projects:
    # Generates a page for each item in collection.
    output: true
  experiences:
    output: true
    sort_by: start_date
    order: descending
  education:
    output: true
    sort_by: start_date
    order: descending

# excerpt_separator: <!-- excerpt -->

# Set timezone
# https://jekyllrb.com/docs/configuration/options/
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/New_York


# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
# title:            Hyde
tagline:          'Front-end developer with over 12 years of experience based in Orlando.'
description:      |
  Lead Front-end Developer at We Are Underground.
url:              https://tylervanschaick.com
baseurl:          /

author:
  name:           'Tyler Van Schaick'
  url:            https://twitter.com/tylervanschaick

paginate:         5

# Custom vars
# version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde

# Add support for excerpts for post
# https://jekyllrb.com/docs/posts/
# excerpt_separator: <!--more-->

skills:
- HTML
- WordPress
- Shopify
- CSS
- JavaScript
- PHP
- React
- Formidable
- Advance Custom Fields
- Klaviyio
- Dawn theme
- Shopify CLI
- Git
- GitHub
- Genesis WordPress Framework
- Web Components
- SCSS
- Sass
- Photoshop
- Illustrator
- DevTools
- Postman
- Express
- NPM
- Heroku
- HelpScout
- Trello
- BEM

site_navigation:
- about
- projects
- experience
- skills